// Geo-Insight — interactive orthographic globe for the landing page.
//
// D3 v7 + TopoJSON. Renders Earth as a thin-line vector globe with the
// top-ten overlooked crises as red hotspots. Drag to rotate. Click a
// hotspot for a sidecar country card. Design language matches
// shared.css: single accent, no textures, rule-coloured boundaries.

(function () {
    "use strict";

    // ─── Top-10 overlooked (HRP-eligible pool, n=22, 2025 cycle).
    //     `rank` is position in the posterior-median ordering (1 = most
    //     overlooked). `ci_width` is the 90 % credible interval width on
    //     the latent — the model's uncertainty about this country.
    //     `cerf` is membership in any CERF UFE allocation 2024–2025.
    //     `explain` fields generated by analysis/llm_explain.py. ──
    const OVERLOOKED = [
        { iso: "HND", name: "Honduras",      rank:  1, ci_width: 0.55, type: "contested · sector-starved", cerf: true,  lat: 15.2,  lon: -86.2 , explain: "Acute needs here go almost entirely unmet, with funding so narrowly concentrated among donors and unevenly spread across sectors that entire response clusters are effectively abandoned. The model places this crisis first among all HRP-eligible countries \u2014 a signal echoed by its independent inclusion on CERF's Underfunded Emergencies list." },
        { iso: "SLV", name: "El Salvador",   rank:  2, ci_width: 0.53, type: "contested · sector-starved", cerf: false, lat: 13.8,  lon: -88.9 , explain: "Funding reaches only a narrow slice of sectors while vast documented need goes almost entirely unmet \u2014 yet this crisis sits outside CERF's Underfunded Emergencies list despite ranking second-most overlooked in the model. That absence warrants scrutiny, as does the model's moderate uncertainty, leaving El Salvador's true neglect an open and pressing question." },
        { iso: "MOZ", name: "Mozambique",    rank:  3, ci_width: 0.52, type: "contested · balanced",       cerf: true,  lat: -18.7, lon:  35.5 , explain: "Millions in Mozambique face acute need that donors are barely reaching, with the model placing it third most overlooked among all active humanitarian response plans. Moderate uncertainty means this ranking could shift, but its presence on CERF's Underfunded Emergencies list independently corroborates the signal." },
        { iso: "SOM", name: "Somalia",       rank:  4, ci_width: 0.51, type: "consensus · overlooked",     cerf: true,  lat:  5.2,  lon:  46.2 , explain: "Across every major sector, Somalia's funding gaps are strikingly uniform \u2014 a signature of systemic neglect rather than any single emergency absorbing attention. The model ranks it fourth most overlooked globally with moderate confidence, a finding reinforced by its independent presence on CERF's Underfunded Emergencies list." },
        { iso: "GTM", name: "Guatemala",     rank:  5, ci_width: 0.58, type: "contested · sector-starved", cerf: false, lat: 15.5,  lon: -90.3 , explain: "Funding for Guatemala's crisis reaches fewer than one in four people in need, yet donor support is heavily concentrated in select sectors, leaving others almost entirely unaddressed. The model ranks this among the five most overlooked crises globally, though its absence from CERF's Underfunded Emergencies list raises an unresolved question about whether that assessment is widely shared." },
        { iso: "NER", name: "Niger",         rank:  6, ci_width: 0.50, type: "consensus · overlooked",     cerf: true,  lat: 17.6,  lon:   8.1 , explain: "Acute need in Niger goes largely unanswered across the board, with funding gaps touching nearly every sector evenly rather than sparing some while starving others. The model places it 6th most overlooked globally with relatively firm confidence \u2014 an assessment corroborated by its inclusion on CERF's Underfunded Emergencies list." },
        { iso: "HTI", name: "Haiti",         rank:  7, ci_width: 0.53, type: "contested · sector-starved", cerf: true,  lat: 18.9,  lon: -72.3 , explain: "Amid compounding gang violence and displacement, Haiti's humanitarian response leaves nearly three-quarters of needs unmet, with funding flowing unevenly across sectors rather than matching the most acute gaps. The model places it seventh-most overlooked globally, though moderate uncertainty suggests its true rank could shift as new data emerge." },
        { iso: "CMR", name: "Cameroon",      rank:  8, ci_width: 0.51, type: "consensus · sector-starved", cerf: true,  lat:  7.4,  lon:  12.4 , explain: "Acute need in Cameroon is going largely unmet, with the model placing it among the eight most overlooked crises across all HRP-eligible countries \u2014 a finding corroborated by its inclusion on CERF's Underfunded Emergencies list. What funding does arrive is distributed unevenly across sectors, leaving critical gaps concentrated in specific clusters rather than shared across the response." },
        { iso: "VEN", name: "Venezuela",     rank:  9, ci_width: 0.49, type: "consensus · overlooked",     cerf: true,  lat:  6.4,  lon: -66.6 , explain: "Funding gaps are spread consistently thin across all sectors here, leaving one of the Western Hemisphere's largest humanitarian crises ranked ninth-most overlooked globally. CERF's independent designation as an underfunded emergency corroborates the model's consensus signal, with nearly 80% of documented need going unmet." },
        { iso: "TCD", name: "Chad",          rank: 10, ci_width: 0.48, type: "consensus · overlooked",     cerf: true,  lat: 15.5,  lon:  18.7 , explain: "Funding gaps are severe and broadly distributed across sectors, leaving millions in one of the world's most acute crises without adequate response. The model places Chad among the ten most overlooked emergencies globally \u2014 a finding reinforced by its independent inclusion on CERF's Underfunded Emergencies list." },
    ];

    const POOL_SIZE = 22;  // HRP-eligible pool, 2025 cycle

    // Default rotation: anchored on Honduras (#1), then drifting east on
    // load. Frames the Latin-America / West-Africa cluster the model
    // surfaces.
    const DEFAULT_ROTATION = [80, -10, 0];

    const COLORS = {
        ocean:     "#ffffff",
        land:      "#fafafa",
        landStroke:"#e8e8e8",
        graticule: "rgba(0, 0, 0, 0.035)",
        edge:      "#888888",
        hotspot:   "#7c1d1d",
        hotspotSel:"#5c1414",
        hotspotDim:"#c9554f",
        label:     "#111111",
        labelMuted:"#555555",
    };

    const container = document.getElementById("globe");
    const panel     = document.getElementById("globe-panel");
    if (!container) return;

    // Sizing — responsive: the container sets the width; height matches.
    const W = container.clientWidth;
    const H = Math.min(W, 560);
    const R = Math.min(W, H) / 2 - 12;
    const cx = W / 2;
    const cy = H / 2;

    const projection = d3.geoOrthographic()
        .scale(R)
        .translate([cx, cy])
        .clipAngle(90)
        .rotate(DEFAULT_ROTATION);

    const path = d3.geoPath(projection);
    const graticule = d3.geoGraticule10();

    const svg = d3.select(container).append("svg")
        .attr("viewBox", `0 0 ${W} ${H}`)
        .attr("width", "100%")
        .attr("height", H)
        .style("display", "block")
        .style("touch-action", "none");

    // Sphere outline + subtle drop
    const defs = svg.append("defs");
    const glow = defs.append("filter").attr("id", "hotspot-glow").attr("x", "-50%").attr("y", "-50%").attr("width", "200%").attr("height", "200%");
    glow.append("feGaussianBlur").attr("stdDeviation", "3").attr("result", "b");
    const glowMerge = glow.append("feMerge");
    glowMerge.append("feMergeNode").attr("in", "b");
    glowMerge.append("feMergeNode").attr("in", "SourceGraphic");

    // Layers (order matters for z-stacking)
    const gSphere    = svg.append("path").attr("id", "sphere");
    const gGraticule = svg.append("path").attr("id", "graticule");
    const gLand      = svg.append("g").attr("id", "land");
    const gEdge      = svg.append("path").attr("id", "edge");
    const gHotspots  = svg.append("g").attr("id", "hotspots");

    gSphere.datum({type: "Sphere"})
        .attr("fill", COLORS.ocean)
        .attr("stroke", "none")
        .attr("d", path);

    gGraticule.datum(graticule)
        .attr("fill", "none")
        .attr("stroke", COLORS.graticule)
        .attr("stroke-width", 0.6)
        .attr("d", path);

    gEdge.datum({type: "Sphere"})
        .attr("fill", "none")
        .attr("stroke", COLORS.edge)
        .attr("stroke-width", 1)
        .attr("d", path);

    // Selected-country fill layer (rendered behind hotspots)
    const selectedFill = svg.insert("path", "#hotspots")
        .attr("fill", "rgba(124, 29, 29, 0.12)")
        .attr("stroke", "none");

    let selectedIso = "HND";

    function render() {
        gSphere.attr("d", path({type: "Sphere"}));
        gGraticule.attr("d", path(graticule));
        gEdge.attr("d", path({type: "Sphere"}));
        gLand.selectAll("path").attr("d", path);

        // Hotspots: project each centroid; fade if on far side.
        const rot = projection.rotate();
        const [lambda, phi] = [-rot[0] * Math.PI / 180, -rot[1] * Math.PI / 180];
        const hotspots = gHotspots.selectAll("g.hotspot")
            .data(OVERLOOKED, d => d.iso);

        const hotspotEnter = hotspots.enter().append("g")
            .attr("class", "hotspot")
            .style("cursor", "pointer")
            .on("click", (_ev, d) => select(d.iso))
            .on("mouseenter", (ev, d) => tooltipShow(ev, d))
            .on("mouseleave", tooltipHide)
            .on("mousemove", tooltipMove);

        hotspotEnter.append("circle").attr("r", 6)
            .attr("fill", COLORS.hotspot)
            .attr("stroke", "#fff")
            .attr("stroke-width", 1.5);

        hotspotEnter.append("circle").attr("class", "halo")
            .attr("r", 10)
            .attr("fill", "none")
            .attr("stroke", COLORS.hotspot)
            .attr("stroke-width", 1.2)
            .attr("opacity", 0.35);

        hotspotEnter.append("text")
            .attr("x", 10).attr("y", 3)
            .attr("font-size", 10)
            .attr("font-family", "Inter, sans-serif")
            .attr("font-weight", 600)
            .attr("fill", COLORS.label)
            .text(d => d.iso);

        const all = hotspots.merge(hotspotEnter);
        all.each(function (d) {
            const coords = [d.lon, d.lat];
            const lonRad = d.lon * Math.PI / 180;
            const latRad = d.lat * Math.PI / 180;
            // Angular distance from current centre (to decide front/back):
            const centerLon = -projection.rotate()[0] * Math.PI / 180;
            const centerLat = -projection.rotate()[1] * Math.PI / 180;
            const cosc = Math.sin(centerLat) * Math.sin(latRad) +
                         Math.cos(centerLat) * Math.cos(latRad) * Math.cos(lonRad - centerLon);
            const visible = cosc > 0.02;
            const [x, y] = projection(coords);
            const isSel  = d.iso === selectedIso;
            d3.select(this)
                .attr("transform", `translate(${x}, ${y})`)
                .attr("display", visible ? null : "none");
            d3.select(this).select("circle:not(.halo)")
                .attr("r", isSel ? 8 : 6)
                .attr("fill", isSel ? COLORS.hotspotSel : COLORS.hotspot);
            d3.select(this).select(".halo")
                .attr("opacity", isSel ? 0.6 : 0.0);
            d3.select(this).select("text")
                .attr("fill", isSel ? COLORS.label : COLORS.labelMuted)
                .attr("font-weight", isSel ? 700 : 600);
        });

        // Selected country outline
        if (selectedCountryFeature) {
            selectedFill.datum(selectedCountryFeature).attr("d", path);
        }
    }

    // ─── Drag to rotate ────────────────────────────────────────────────
    let dragStart = null;
    let rotationStart = null;
    svg.call(
        d3.drag()
            .on("start", (ev) => {
                dragStart = [ev.x, ev.y];
                rotationStart = projection.rotate();
            })
            .on("drag", (ev) => {
                if (!dragStart) return;
                const dx = ev.x - dragStart[0];
                const dy = ev.y - dragStart[1];
                const sensitivity = 0.3;
                const lambda = rotationStart[0] + dx * sensitivity;
                const phi = Math.max(-70, Math.min(70, rotationStart[1] - dy * sensitivity));
                projection.rotate([lambda, phi, rotationStart[2]]);
                render();
            })
            .on("end", () => { dragStart = null; })
    );

    // ─── Slow idle rotation, pauses when user interacts ───────────────
    let autoRotating = true;
    let lastTs = 0;
    svg.on("pointerdown", () => { autoRotating = false; });

    function tick(ts) {
        if (!lastTs) lastTs = ts;
        const dt = ts - lastTs;
        lastTs = ts;
        if (autoRotating) {
            const rot = projection.rotate();
            projection.rotate([rot[0] + dt * 0.008, rot[1], rot[2]]);
            render();
        }
        requestAnimationFrame(tick);
    }

    // ─── Load world topology + render land ─────────────────────────────
    let countries = null;
    let selectedCountryFeature = null;

    d3.json("world-110m.json").then((world) => {
        countries = topojson.feature(world, world.objects.countries);
        gLand.selectAll("path")
            .data(countries.features)
            .join("path")
            .attr("fill", COLORS.land)
            .attr("stroke", COLORS.landStroke)
            .attr("stroke-width", 0.6)
            .attr("d", path);
        select(selectedIso);
        render();
        requestAnimationFrame(tick);
    });

    // ─── Selection + sidecar panel ─────────────────────────────────────
    const ISO_NUMERIC = {
        HND: "340", SLV: "222", MOZ: "508", SOM: "706", GTM: "320",
        NER: "562", HTI: "332", CMR: "120", VEN: "862", TCD: "148",
    };

    function select(iso) {
        selectedIso = iso;
        if (countries) {
            const num = ISO_NUMERIC[iso];
            selectedCountryFeature = countries.features.find((f) => f.id === num) || null;
        }
        const d = OVERLOOKED.find((x) => x.iso === iso);
        if (panel && d) {
            panel.innerHTML = panelHTML(d);
        }
        render();
    }

    const TIPS = {
        "IQR":             "Inter-quartile range across four donor-preference profiles — higher values mean more disagreement on this country's priority.",
        "sector-starved":  "Aid is concentrated in a few sectors, leaving others critically underfunded.",
        "overlooked":      "Underfunding is broad and even across all humanitarian sectors.",
        "contested":       "Donor profiles disagree significantly on this country's priority ranking.",
        "consensus":       "Donor profiles broadly agree this crisis is severely underfunded.",
        "coverage shortfall": "The gap between humanitarian funding received and the amount formally requested.",
        "balanced":           "Funding gaps are distributed relatively evenly across humanitarian sectors — no single sector is disproportionately starved.",
    };

    function applyTips(text) {
        let out = text;
        for (const [term, tip] of Object.entries(TIPS)) {
            out = out.replace(
                new RegExp(`\\b${term}\\b`, "gi"),
                `<span class="term" data-tip="${tip}">$&</span>`
            );
        }
        return out;
    }

    function panelHTML(d) {
        const cerf = d.cerf
            ? `<span class="panel-chip chip-on">CERF UFE pick (2024–25)</span>`
            : `<span class="panel-chip chip-off">Not picked by CERF UFE</span>`;
        const explain = d.explain
            ? `<p class="panel-explain">${applyTips(d.explain)}</p>`
            : "";
        const links = `
            <div class="panel-links">
                <a href="https://reliefweb.int/country/${d.iso.toLowerCase()}" target="_blank" rel="noopener">ReliefWeb updates ↗</a>
                <a href="http://localhost:8502/?mode=profile&country=${d.iso}" target="_blank" rel="noopener">Country profile ↗</a>
            </div>`;
        return `
            <div class="panel-eyebrow">Selected country</div>
            <div class="panel-name">${d.name}</div>
            <div class="panel-iso">${d.iso}</div>

            <div class="panel-grid">
                <div class="panel-metric">
                    <div class="panel-metric-label">Posterior rank</div>
                    <div class="panel-metric-value">${d.rank}<span style="font-size: 0.55em; color: var(--muted); font-weight: 400; margin-left: 4px;">of ${POOL_SIZE}</span></div>
                </div>
                <div class="panel-metric">
                    <div class="panel-metric-label">90 % CI width</div>
                    <div class="panel-metric-value">${d.ci_width.toFixed(2)}</div>
                </div>
            </div>

            <div class="panel-type">${applyTips(d.type)}</div>
            <div class="panel-chips">${cerf}</div>
            ${explain}
            ${links}

            <p class="panel-note">
                Position in the 2025-cycle Bayesian posterior across ${POOL_SIZE} HRP-eligible
                countries (those with an active humanitarian response plan). The 90 % CI width
                on the latent says how confidently the model places this crisis — wide bands
                mean the data alone cannot reliably distinguish this country from its neighbours
                in the ranking.
            </p>
        `;
    }

    // ─── Tooltip (hover) ───────────────────────────────────────────────
    const tt = document.getElementById("globe-tooltip");
    function tooltipShow(ev, d) {
        if (!tt) return;
        tt.textContent = `${d.name} · rank ${d.rank} of ${POOL_SIZE}`;
        tt.style.opacity = "1";
        tooltipMove(ev);
    }
    function tooltipMove(ev) {
        if (!tt) return;
        const rect = container.getBoundingClientRect();
        tt.style.left = (ev.clientX - rect.left + 12) + "px";
        tt.style.top  = (ev.clientY - rect.top  - 8)  + "px";
    }
    function tooltipHide() {
        if (!tt) return;
        tt.style.opacity = "0";
    }
})();
